### ISSUE TITLE
Analysis - Initial EDA

### ISSUE THREAD

**Issue by FionaC124** [FionaC124/dsci310-group-analysis#9]

**Comment by pbrar17** [comment]
Did some intial EDA + read in the data

**Comment by FionaC124** [comment]
- loads data from the original source on the web
- wrangles and cleans the data from it’s original (downloaded) format to the format necessary for the planned classification or clustering analysis
- performs a summary of the data set that is relevant for exploratory data analysis related to the planned classification analysis
